run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
linters:
  disable-all: true
  enable:
  # default linters
  - deadcode
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  # - structcheck # disabled due to Go 1.18
  - typecheck
  - unused
  - varcheck

  # additional linters
  - errorlint
  - errname
  - gocyclo
  - goimports
  - misspell
  - gofmt
  - importas
  - goconst
  - gocritic
  # - godox
  # - gosec
  - misspell
  # - predeclared
